FROM python:3.12.0a4-bullseye


# VOLUME ["/sharedFiles1"]
WORKDIR /container1

COPY requirements.txt .
RUN pip3 install -r ./requirements.txt
# COPY /sharedFiles1/container1/container1.py .
COPY . /container1
CMD ["python3", "container1.py"]

EXPOSE 5000